ALTER TABLE "User"
  ADD COLUMN "dateOfBirth" DATE,
  ADD COLUMN "termsAcceptedAt" TIMESTAMP(3),
  ADD COLUMN "termsAcceptedVersion" TEXT,
  ADD COLUMN "personalDataConsentAt" TIMESTAMP(3),
  ADD COLUMN "personalDataConsentVersion" TEXT,
  ADD COLUMN "personalDataConsentIp" TEXT,
  ADD COLUMN "personalDataConsentUserAgent" TEXT,
  ADD COLUMN "publicDataConsentAt" TIMESTAMP(3),
  ADD COLUMN "publicDataConsentVersion" TEXT,
  ADD COLUMN "publicDataConsentIp" TEXT,
  ADD COLUMN "publicDataConsentUserAgent" TEXT,
  ADD COLUMN "publicDataConsentCategories" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "guardianFullName" TEXT,
  ADD COLUMN "guardianEmail" TEXT,
  ADD COLUMN "guardianConsentAt" TIMESTAMP(3),
  ADD COLUMN "guardianConsentVersion" TEXT,
  ADD COLUMN "guardianConsentIp" TEXT,
  ADD COLUMN "guardianConsentUserAgent" TEXT;
