"use client";

import { PlayoffType } from "@prisma/client";
import { Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { normalizeStageGraph, type StageGraphBlueprint, type StageGraphStageType } from "@/lib/tournament-stage-graph";

function nextId(prefix: string) { return `${prefix}_${Date.now()}`; }

export function StageGraphEditor({ value, onChange }: { value: StageGraphBlueprint; onChange: (value: StageGraphBlueprint) => void }) {
  const [graph, setGraph] = useState(() => normalizeStageGraph(value));
  useEffect(() => setGraph(normalizeStageGraph(value)), [value]);
  const update = (fn: (value: StageGraphBlueprint) => StageGraphBlueprint) => setGraph((current) => { const next = fn(current); onChange(next); return next; });
  const stages = graph.stages;
  const playoffs = stages.filter((stage) => stage.type === "PLAYOFF");
  return <section className="space-y-4 rounded-xl border border-primary/15 bg-primary/[0.04] p-4">
    <div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-white">Схема этапов</h3><p className="text-xs text-zinc-500">Настройте этапы и переходы.</p></div><Button type="button" variant="outline" onClick={() => update((current) => ({ ...current, stages: [...current.stages, { id: nextId("stage"), name: `Этап ${current.stages.length + 1}`, type: "GROUPS", divisionsCount: 1, participantsPerDivision: null, roundsCount: 1, matchesPerOpponent: null }] }))}><Plus className="mr-2 h-4 w-4" />Добавить этап</Button></div>
    <div className="grid gap-3 lg:grid-cols-2">{stages.map((stage) => <div key={stage.id} className="space-y-2 rounded-lg border border-white/10 bg-black/20 p-3"><div className="flex gap-2"><Input aria-label="Название этапа" value={stage.name} onChange={(event) => update((current) => ({ ...current, stages: current.stages.map((item) => item.id === stage.id ? { ...item, name: event.target.value } : item) }))} /><select aria-label="Тип этапа" value={stage.type} onChange={(event) => update((current) => ({ ...current, stages: current.stages.map((item) => item.id === stage.id ? { ...item, type: event.target.value as StageGraphStageType, playoffType: event.target.value === "PLAYOFF" ? PlayoffType.SINGLE : undefined } : item) }))}><option value="GROUPS">Группы</option><option value="LEAGUE">Лига</option><option value="PLAYOFF">Плей-офф</option></select>{stages.length > 1 ? <Button type="button" variant="ghost" size="icon" aria-label="Удалить этап" onClick={() => update((current) => ({ ...current, stages: current.stages.filter((item) => item.id !== stage.id), transitions: current.transitions.filter((item) => item.fromStageId !== stage.id && item.toStageId !== stage.id) }))}><Trash2 className="h-4 w-4" /></Button> : null}</div>{stage.type !== "PLAYOFF" ? <div className="grid grid-cols-3 gap-2"><Input aria-label="Количество групп" type="number" min={1} max={32} value={stage.divisionsCount} onChange={(event) => update((current) => ({ ...current, stages: current.stages.map((item) => item.id === stage.id ? { ...item, divisionsCount: Math.max(1, Number(event.target.value) || 1) } : item) }))} /><Input aria-label="Участников в группе" type="number" min={2} max={64} value={stage.participantsPerDivision ?? ""} onChange={(event) => update((current) => ({ ...current, stages: current.stages.map((item) => item.id === stage.id ? { ...item, participantsPerDivision: event.target.value ? Math.max(2, Number(event.target.value)) : null } : item) }))} /><Input aria-label="Количество туров" type="number" min={1} max={128} value={stage.roundsCount} onChange={(event) => update((current) => ({ ...current, stages: current.stages.map((item) => item.id === stage.id ? { ...item, roundsCount: Math.max(1, Number(event.target.value) || 1) } : item) }))} /></div> : null}</div>)}</div>
    <div className="space-y-2 border-t border-white/10 pt-3"><div className="flex justify-between"><span className="text-xs text-zinc-300">Переходы</span><Button type="button" variant="ghost" size="sm" disabled={stages.length < 2} onClick={() => update((current) => ({ ...current, transitions: [...current.transitions, { id: nextId("transition"), fromStageId: stages[0]?.id ?? "", toStageId: stages[1]?.id ?? "", result: "RANK", fromDivisionIndex: 1, fromRank: 1, toRank: 1, toDivisionIndex: 1, targetBracket: "upper" }] }))}><Plus className="mr-1 h-3 w-3" />Добавить</Button></div>{graph.transitions.map((transition) => <div key={transition.id} className="grid gap-2 sm:grid-cols-5"><select aria-label="Исходный этап" value={transition.fromStageId} onChange={(event) => update((current) => ({ ...current, transitions: current.transitions.map((item) => item.id === transition.id ? { ...item, fromStageId: event.target.value } : item) }))}>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select><select aria-label="Целевой этап" value={transition.toStageId} onChange={(event) => update((current) => ({ ...current, transitions: current.transitions.map((item) => item.id === transition.id ? { ...item, toStageId: event.target.value } : item) }))}>{stages.map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</select><select aria-label="Тип результата" value={transition.result} onChange={(event) => update((current) => ({ ...current, transitions: current.transitions.map((item) => item.id === transition.id ? { ...item, result: event.target.value as typeof item.result } : item) }))}><option value="RANK">Место</option><option value="WINNER">Победитель</option><option value="RUNNER_UP">Финалист</option><option value="THIRD_PLACE">3-е место</option></select>{transition.result === "RANK" ? <><Input aria-label="От места" type="number" value={transition.fromRank ?? 1} onChange={(event) => update((current) => ({ ...current, transitions: current.transitions.map((item) => item.id === transition.id ? { ...item, fromRank: Math.max(1, Number(event.target.value) || 1), toRank: Math.max((item.toRank ?? 1), Number(event.target.value) || 1) } : item) }))} /><Input aria-label="До места" type="number" value={transition.toRank ?? transition.fromRank ?? 1} onChange={(event) => update((current) => ({ ...current, transitions: current.transitions.map((item) => item.id === transition.id ? { ...item, toRank: Math.max((item.fromRank ?? 1), Number(event.target.value) || (item.fromRank ?? 1)) } : item) }))} /></> : null}</div>)}</div>
    {playoffs.length >= 2 ? <div className="space-y-2 rounded-lg border border-amber-300/20 bg-amber-300/[0.06] p-3"><label className="flex items-center gap-3 text-sm text-amber-100"><input type="checkbox" className="h-4 w-4 accent-primary" checked={graph.superCup.enabled} onChange={(event) => update((current) => ({ ...current, superCup: { ...current.superCup, enabled: event.target.checked, sourcePlayoffIds: current.superCup.sourcePlayoffIds.length >= 2 ? current.superCup.sourcePlayoffIds : playoffs.map((stage) => stage.id) } }))} />Включить Суперкубок</label>{graph.superCup.enabled ? <div className="grid gap-2 sm:grid-cols-2">{playoffs.map((stage) => <label key={stage.id} className="flex items-center gap-2 text-xs text-zinc-300"><input type="checkbox" className="h-4 w-4 accent-primary" checked={graph.superCup.sourcePlayoffIds.includes(stage.id)} onChange={(event) => update((current) => ({ ...current, superCup: { ...current.superCup, sourcePlayoffIds: event.target.checked ? [...current.superCup.sourcePlayoffIds, stage.id] : current.superCup.sourcePlayoffIds.filter((id) => id !== stage.id) } }))} />{stage.name}</label>)}</div> : null}</div> : null}
  </section>;
}
