-- Add clubs for the recently uploaded top-five league badges.
INSERT INTO "Club" ("id","slug","name","imagePath","leagueId","isRegistrationEnabled","isInGameEnabled","sortOrder","createdAt","updatedAt")
SELECT 'club_' || x.slug, x.slug, x.name, '/club-badges/thumbs/' || x.slug || '.webp', l.id, true, true, 100, NOW(), NOW()
FROM (VALUES
  ('bournemouth-big','Борнмут','premier-league'), ('brentford-big-768x768','Брентфорд','premier-league'), ('everton-big-768x786','Эвертон','premier-league'),
  ('valencia','Валенсия','la-liga'), ('Real_Zaragoza_logo.svg','Реал Сарагоса','la-liga'), ('Deportivo-La-Coruna (1)','Депортиво Ла-Корунья','la-liga'), ('getafe-big','Хетафе','la-liga'), ('osasuna-big','Осасуна','la-liga'), ('rayo-vallecano-big-768x682','Райо Вальекано','la-liga'), ('mallorca-big','Мальорка','la-liga'), ('real-valladolid-big-2022','Реал Вальядолид','la-liga'), ('huesca-big','Уэска','la-liga'),
  ('lyon-big-2022','Лион','ligue-1'), ('lille-big-768x731','Лилль','ligue-1'), ('nice-big','Ницца','ligue-1'), ('rennes-big','Ренн','ligue-1'), ('lens-big','Ланс','ligue-1'), ('nantes-big-2020','Нант','ligue-1'), ('strasbourg-big-768x768','Страсбур','ligue-1'), ('auxerre-big','Осер','ligue-1'), ('brest-big','Брест','ligue-1'), ('clermont-big','Клермон','ligue-1'), ('lorient-big','Лорьян','ligue-1'), ('metz-big-2021','Мец','ligue-1'), ('reims-big-2020','Реймс','ligue-1'), ('toulouse-big-768x768','Тулуза','ligue-1'),
  ('stuttgart-big','Штутгарт','bundesliga'), ('wolfsburg-big-768x768','Вольфсбург','bundesliga'), ('augsburg-big','Аугсбург','bundesliga'), ('freiburg-big','Фрайбург','bundesliga'), ('hoffenheim-big','Хоффенхайм','bundesliga'), ('mainz-05-big-768x715','Майнц 05','bundesliga'), ('union-berlin-big-768x280','Унион Берлин','bundesliga'), ('hannover-96-big-768x677','Ганновер 96','bundesliga'), ('1._FC_Nürnberg_logo.svg','Нюрнберг','bundesliga'),
  ('bologna-big','Болонья','serie-a'), ('fiorentina-big-2022-768x768','Фиорентина','serie-a'), ('lazio-big-443x300','Лацио','serie-a'), ('napoli-big-2024-768x768','Наполи','serie-a'), ('torino-big','Торино','serie-a'), ('sampdoria-big','Сампдория','serie-a'), ('parma-big','Парма','serie-a'), ('sassuolo-big','Сассуоло','serie-a'), ('cagliari-big','Кальяри','serie-a'), ('lecce-big-2023','Лечче','serie-a'), ('empoli-big-2021','Эмполи','serie-a'), ('Hellas_verona_logo_3','Верона','serie-a')
) AS x(slug,name,league_slug)
JOIN "League" l ON l.slug = x.league_slug
ON CONFLICT ("slug") DO UPDATE SET "name" = EXCLUDED."name", "imagePath" = EXCLUDED."imagePath", "leagueId" = EXCLUDED."leagueId", "isRegistrationEnabled" = true, "isInGameEnabled" = true, "updatedAt" = NOW();
