import Link from "next/link";
import { BarChart3, Boxes, CircleDollarSign, PackageCheck, Settings2, ShieldCheck, ShoppingBag, Star, Users } from "lucide-react";
import { requireAnyPermission } from "@/lib/auth/session";
import { getShopAdminDashboard } from "@/lib/shop/admin";
import { defaultShopSettings } from "@/lib/shop/config";
import { formatShopMoney, shopOrderStatusLabels } from "@/lib/shop/format";
import { getShopPermissionIds } from "@/lib/shop/permissions";
import styles from "@/components/shop/shop.module.css";

export const dynamic = "force-dynamic";

export default async function AdminShopPage(props: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireAnyPermission(["shop.support", "shop.manage"]);
  const params = await props.searchParams;
  const days = Number.parseInt(String(params.days ?? "30"), 10);
  const [data, permissions] = await Promise.all([getShopAdminDashboard(days), getShopPermissionIds(session.user.id)]);
  const canManage = permissions.includes("shop.manage");
  const settings = data.settings ?? defaultShopSettings;
  return <div className="space-y-6">
    {typeof params.saved === "string" ? <div className={styles.success}><ShieldCheck /> Изменения магазина сохранены.</div> : null}
    {typeof params.error === "string" ? <div className={styles.warning}>{params.error}</div> : null}

    <section><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Период: {days} дней</p><h2 className={styles.sectionTitle}>Показатели магазина</h2></div><form><select name="days" className={styles.select} defaultValue={days}><option value="7">7 дней</option><option value="30">30 дней</option><option value="90">90 дней</option><option value="365">Год</option></select><button className={styles.buttonSecondary}>Применить</button></form></div><div className={styles.statGrid}>
      {[{ label: "Выручка", value: formatShopMoney(data.metrics.revenueMinor), icon: CircleDollarSign }, { label: "Заказы", value: data.metrics.orders, icon: ShoppingBag }, { label: "Средний чек", value: formatShopMoney(data.metrics.averageOrderMinor), icon: BarChart3 }, { label: "Завершены", value: data.metrics.completed, icon: PackageCheck }, { label: "Успешные оплаты", value: data.metrics.successfulPayments, icon: ShieldCheck }, { label: "Возвраты", value: data.metrics.refunds, icon: CircleDollarSign }, { label: "Споры", value: data.metrics.disputes, icon: ShieldCheck }, { label: "Отзывы на модерации", value: data.metrics.pendingReviews, icon: Star }].map((metric) => <article className={styles.statCard} key={metric.label}><metric.icon size={18} /><span>{metric.label}</span><strong>{metric.value}</strong></article>)}
    </div></section>

    {canManage ? <section className={styles.adminGrid}>
      <form action="/api/admin/shop" method="post" className={styles.adminCard}><input type="hidden" name="_action" value="saveSettings" /><h2><Settings2 size={17} /> Настройки</h2><div className={styles.formRow}><label className={styles.checkLabel}><input type="checkbox" name="isEnabled" value="true" defaultChecked={settings.isEnabled} /> Магазин включён</label><label className={styles.checkLabel}><input type="checkbox" name="maintenanceMode" value="true" defaultChecked={settings.maintenanceMode} /> Техработы</label><label className={styles.checkLabel}><input type="checkbox" name="showHomeBlock" value="true" defaultChecked={settings.showHomeBlock} /> Блок на главной</label><label className={styles.checkLabel}><input type="checkbox" name="autoCompleteEnabled" value="true" defaultChecked={settings.autoCompleteEnabled} /> Автозавершение</label></div><div className={styles.formRow}><label className={styles.fieldLabel}>Валюта<input className={styles.input} name="currency" defaultValue={settings.currency} /></label><label className={styles.fieldLabel}>Версия условий<input className={styles.input} name="termsVersion" defaultValue={settings.termsVersion} /></label><label className={styles.fieldLabel}>Минимум, ₽<input className={styles.input} name="minimumOrder" defaultValue={settings.minimumOrderMinor / 100} /></label><label className={styles.fieldLabel}>Максимум, ₽<input className={styles.input} name="maximumOrder" defaultValue={settings.maximumOrderMinor / 100} /></label></div><div className={styles.formRow}><label className={styles.fieldLabel}>Оплата, мин<input className={styles.input} name="paymentTimeoutMinutes" type="number" defaultValue={settings.paymentTimeoutMinutes} /></label><label className={styles.fieldLabel}>Принятие, мин<input className={styles.input} name="sellerAcceptTimeoutMinutes" type="number" defaultValue={settings.sellerAcceptTimeoutMinutes} /></label><label className={styles.fieldLabel}>Выполнение, мин<input className={styles.input} name="fulfillmentTimeoutMinutes" type="number" defaultValue={settings.fulfillmentTimeoutMinutes} /></label><label className={styles.fieldLabel}>Проверка, мин<input className={styles.input} name="buyerConfirmTimeoutMinutes" type="number" defaultValue={settings.buyerConfirmTimeoutMinutes} /></label></div><label className={styles.fieldLabel}>Контакты поддержки<input className={styles.input} name="supportContact" defaultValue={settings.supportContact ?? ""} /></label><input type="hidden" name="cancellationEnabled" value="true" /><input type="hidden" name="reviewModerationEnabled" value="true" /><button className={styles.button}>Сохранить настройки</button></form>

      <form action="/api/admin/shop" method="post" className={styles.adminCard}><input type="hidden" name="_action" value="createCategory" /><h2><Boxes size={17} /> Новая категория</h2><div className={styles.formRow}><label className={styles.fieldLabel}>Название<input className={styles.input} name="name" required minLength={2} /></label><label className={styles.fieldLabel}>Slug<input className={styles.input} name="slug" required pattern="[a-z0-9-]+" /></label></div><label className={styles.fieldLabel}>Описание<textarea className={styles.textarea} name="description" /></label><label className={styles.fieldLabel}>Порядок<input className={styles.input} name="sortOrder" type="number" defaultValue="0" /></label><button className={styles.button}>Создать категорию</button></form>

      <form action="/api/admin/shop" method="post" className={styles.adminCard}><input type="hidden" name="_action" value="createProduct" /><h2><ShoppingBag size={17} /> Новый товар</h2><div className={styles.formRow}><label className={styles.fieldLabel}>Категория<select className={styles.select} name="categoryId" required>{data.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className={styles.fieldLabel}>Тип<select className={styles.select} name="type"><option value="IN_GAME">Внутриигровой</option><option value="PROMOTIONAL">Акционный</option></select></label><label className={styles.fieldLabel}>Название<input className={styles.input} name="title" required /></label><label className={styles.fieldLabel}>Slug<input className={styles.input} name="slug" required pattern="[a-z0-9-]+" /></label><label className={styles.fieldLabel}>SKU<input className={styles.input} name="sku" required /></label><label className={styles.fieldLabel}>Вариант<input className={styles.input} name="variantName" defaultValue="Стандартный" /></label><label className={styles.fieldLabel}>Цена, ₽<input className={styles.input} name="price" required inputMode="decimal" /></label><label className={styles.fieldLabel}>Остаток<input className={styles.input} name="stockQuantity" type="number" min="0" defaultValue="0" /></label><label className={styles.fieldLabel}>Время, мин<input className={styles.input} name="estimatedMinutes" type="number" min="1" defaultValue="30" /></label><label className={styles.fieldLabel}>URL изображения<input className={styles.input} name="imageUrl" type="url" /></label></div><label className={styles.checkLabel}><input type="checkbox" name="unlimited" value="true" /> Неограниченный остаток</label><label className={styles.checkLabel}><input type="checkbox" name="isActive" value="true" /> Сразу опубликовать</label><label className={styles.fieldLabel}>Кратко<input className={styles.input} name="shortDescription" required /></label><label className={styles.fieldLabel}>Описание<textarea className={styles.textarea} name="description" required /></label><label className={styles.fieldLabel}>Условия получения<textarea className={styles.textarea} name="fulfillmentTerms" required /></label><button className={styles.button}>Создать товар</button></form>

      <form action="/api/admin/shop" method="post" className={styles.adminCard}><input type="hidden" name="_action" value="addSeller" /><h2><Users size={17} /> Добавить продавца</h2><label className={styles.fieldLabel}>Публичный ID пользователя<input className={styles.input} name="publicId" required /></label><div className={styles.formRow}><label className={styles.fieldLabel}>Активных заказов<input className={styles.input} name="maxActiveOrders" type="number" defaultValue="3" /></label><label className={styles.fieldLabel}>Комиссия, bps<input className={styles.input} name="commissionBps" type="number" min="0" max="10000" defaultValue="3000" /></label></div><button className={styles.button}>Назначить продавцом</button></form>

      <form action="/api/admin/shop" method="post" className={styles.adminCard}><input type="hidden" name="_action" value="createPromotion" /><h2>Новая акция</h2><label className={styles.fieldLabel}>Название<input className={styles.input} name="name" required /></label><label className={styles.fieldLabel}>Товар<select className={styles.select} name="productId">{data.products.map((product) => <option key={product.id} value={product.id}>{product.title}</option>)}</select></label><div className={styles.formRow}><label className={styles.fieldLabel}>Тип<select className={styles.select} name="discountType"><option value="PERCENT">Процент</option><option value="FIXED">Фиксированная сумма</option></select></label><label className={styles.fieldLabel}>Скидка<input className={styles.input} name="discountValue" required /></label><label className={styles.fieldLabel}>Начало<input className={styles.input} name="startsAt" type="datetime-local" required /></label><label className={styles.fieldLabel}>Конец<input className={styles.input} name="endsAt" type="datetime-local" required /></label></div><label className={styles.checkLabel}><input name="showCountdown" type="checkbox" value="true" /> Показывать реальный таймер</label><button className={styles.button}>Создать акцию</button></form>

      <form action="/api/admin/shop" method="post" className={styles.adminCard}><input type="hidden" name="_action" value="createPromoCode" /><h2>Новый промокод</h2><div className={styles.formRow}><label className={styles.fieldLabel}>Код<input className={styles.input} name="code" required /></label><label className={styles.fieldLabel}>Тип<select className={styles.select} name="discountType"><option value="PERCENT">Процент</option><option value="FIXED">Фиксированная сумма</option></select></label><label className={styles.fieldLabel}>Скидка<input className={styles.input} name="discountValue" required /></label><label className={styles.fieldLabel}>Минимальная сумма<input className={styles.input} name="minimumSubtotal" defaultValue="0" /></label><label className={styles.fieldLabel}>Начало<input className={styles.input} name="startsAt" type="datetime-local" required /></label><label className={styles.fieldLabel}>Конец<input className={styles.input} name="endsAt" type="datetime-local" required /></label><label className={styles.fieldLabel}>Общий лимит<input className={styles.input} name="totalUsageLimit" type="number" /></label><label className={styles.fieldLabel}>На пользователя<input className={styles.input} name="perUserUsageLimit" type="number" defaultValue="1" /></label></div><label className={styles.checkLabel}><input name="newUsersOnly" type="checkbox" value="true" /> Только первая покупка</label><button className={styles.button}>Создать промокод</button></form>
    </section> : <div className={styles.notice}><ShieldCheck /> У вас есть права поддержки заказов без доступа к ценам, каталогу и продавцам.</div>}

    <section><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Каталог</p><h2 className={styles.sectionTitle}>Товары</h2></div><Link className={styles.buttonSecondary} href="/shop">Открыть магазин</Link></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Товар</th><th>Категория</th><th>Цена</th><th>Остаток</th><th>Статус</th><th /></tr></thead><tbody>{data.products.map((product) => <tr key={product.id}><td>{product.title}<br /><small>{product.slug}</small></td><td>{product.category.name}</td><td>{formatShopMoney(product.variants[0]?.priceMinor ?? 0)}</td><td>{product.variants[0]?.stockMode === "UNLIMITED" ? "∞" : product.variants[0]?.stockQuantity ?? 0}</td><td><span className={styles.status}>{product.isActive ? "Опубликован" : "Черновик"}</span></td><td>{canManage ? <form action="/api/admin/shop" method="post"><input type="hidden" name="_action" value="toggleProduct" /><input type="hidden" name="id" value={product.id} /><button className={styles.cardLink}>{product.isActive ? "Скрыть" : "Опубликовать"}</button></form> : null}</td></tr>)}</tbody></table></div></section>

    <section><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Контекстные роли</p><h2 className={styles.sectionTitle}>Продавцы</h2></div></div><div className={styles.adminGrid}>{data.sellers.map((seller) => <article className={styles.adminCard} key={seller.id}><h2>{seller.user.name ?? seller.user.publicId}</h2><p className={styles.sectionText}>@{seller.user.telegramUsername ?? "Telegram не указан"} · Активных: {seller._count.orders}/{seller.maxActiveOrders}</p><span className={styles.status}>{seller.isActive ? "Работает" : "Отключён"}</span>{canManage ? <><form action="/api/admin/shop" method="post" className={styles.inlineActions}><input type="hidden" name="_action" value="toggleSeller" /><input type="hidden" name="id" value={seller.id} /><button className={styles.buttonSecondary}>{seller.isActive ? "Отключить" : "Включить"}</button></form><form action="/api/admin/shop" method="post" className={styles.form}><input type="hidden" name="_action" value="assignSellerProduct" /><input type="hidden" name="sellerId" value={seller.id} /><select className={styles.select} name="productId">{data.products.map((product) => <option value={product.id} key={product.id}>{product.title}</option>)}</select><button className={styles.buttonSecondary}>Назначить товар</button></form></> : null}</article>)}</div></section>

    <section><div className={styles.sectionHead}><div><p className={styles.eyebrow}>Последние {days} дней</p><h2 className={styles.sectionTitle}>Заказы и споры</h2></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Заказ</th><th>Покупатель</th><th>Продавец</th><th>Статус</th><th>Сумма</th><th /></tr></thead><tbody>{data.orders.map((order) => <tr key={order.id}><td>{order.orderNumber}<br /><small>{order.items[0]?.productTitle}</small></td><td>{order.buyer.name ?? "Пользователь"}</td><td>{order.seller?.user.name ?? "Не назначен"}</td><td><span className={styles.status}>{shopOrderStatusLabels[order.status]}</span></td><td>{formatShopMoney(order.totalMinor, order.currency)}</td><td><Link className={styles.cardLink} href={`/shop/orders/${order.id}`}>Открыть</Link></td></tr>)}</tbody></table></div></section>

    {data.orders.some((order) => order.status === "DISPUTE") ? <section>
      <div className={styles.sectionHead}><div><p className={styles.eyebrow}>Требуют решения</p><h2 className={styles.sectionTitle}>Открытые споры</h2></div></div>
      <div className={styles.adminGrid}>{data.orders.filter((order) => order.status === "DISPUTE").map((order) => <form action="/api/admin/shop" method="post" className={styles.adminCard} key={order.id}>
        <input type="hidden" name="_action" value="resolveDispute" /><input type="hidden" name="orderId" value={order.id} />
        <h2>{order.orderNumber}</h2><p className={styles.sectionText}>{order.items[0]?.productTitle} · {formatShopMoney(order.totalMinor, order.currency)}</p>
        <label className={styles.fieldLabel}>Решение<textarea className={styles.textarea} name="resolution" minLength={5} required /></label>
        <label className={styles.fieldLabel}>Исход<select className={styles.select} name="targetStatus"><option value="IN_PROGRESS">Повторное выполнение</option><option value="COMPLETED">Завершить заказ</option><option value="REFUND_PENDING">Создать возврат</option><option value="CANCELLED">Отменить</option></select></label>
        <label className={styles.fieldLabel}>Сумма возврата, ₽ (если нужна)<input className={styles.input} name="refundAmount" inputMode="decimal" /></label>
        <button className={styles.button}>Зафиксировать решение</button>
      </form>)}</div>
    </section> : null}

    <div className={styles.warning}><ShieldCheck /><div><strong>Юридическая проверка обязательна</strong><br />Тексты правил магазина, возвратов, споров и обработки игровых данных являются структурой проекта и должны быть проверены юристом до включения магазина.</div></div>
  </div>;
}
